# Generated by Django 4.2.27 on 2026-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('subtitle', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('img_url', models.CharField(max_length=250)),
            ],
        ),
    ]
